Feature/team
YAPP-admin/attendance-android pull request #53
Opened 2022-02-27 16:51 UTC by junieberry

**Description**

팀 선택 화면 구현

- 뒤로가기는 실명 입력 화면 구현 이후 구현하겠습니다
- 확인 버튼이 disabled 되어 있을 때 어떻게 클릭 이벤트를 막는지 궁금합니다..!
- `Flexbox` 레이아웃을 사용하고 싶어서 `flowLayout`을 사용했습니다!

**Screen Shots**

| Screen Shot | Screen Shot |
| ----------- | ----------- |
|   <img src ="https://user-images.githubusercontent.com/67185391/155891444-b03efc4c-cf67-4f3c-938c-4bbf42b0cfca.png">   | ![image](https://user-images.githubusercontent.com/67185391/155891469-5b115f53-6704-41a5-b8e1-82af5938e12b.png)
         |

**Check List**

- [ ] CI/CD 통과여부
- [ ] Develop Mege 시 Squash and Merge 형태로 넣어주세요!
- [ ] 1Approve 이상 Merge
- [ ] Unit Test 작성
- [ ] 연관된 이슈를 PR에 연결해주세요.

2022-02-27 17:01 UTC, LuvJoy commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +fun TeamNumberOption(uiState: TeamContract.TeamUiState, viewModel: TeamViewModel) {
```suggestion
fun TeamNumberOption(uiState: TeamContract.TeamUiState, onClick: (TeamContract.TeamUiEvent) -> Unit) {
```
해당 컴포저블에 파라미터로 viewModel이 있으면 테스트하기 힘들것 같아요!
지금 클릭 이벤트를 위해서 viewModel을 넣어주기 보다는
클릭 이벤트를 호이스팅 하는게 좋은 방향일것 같아요!

2022-02-27 17:09 UTC, LuvJoy commented
`확인 버튼이 disabled 되어 있을 때 어떻게 클릭 이벤트를 막는지 궁금합니다..!`

-> uiState에 confirmClickable (예를들어) 라는 변수를 두고
해당 버튼에 onClick에다가 confirmClickable이 true일때만 Event를 발생시키게끔 하면 될것같아요!

2022-02-27 17:13 UTC, LuvJoy approved these changes

2022-02-27 17:16 UTC, LuvJoy approved these changes
👍 👍 👍 👍

2022-02-28 03:29 UTC, jsh-me commented on buildSrc/src/main/java/com/yapp/buildsrc/Dependencies.kt
> +        const val FLOW_LAYOUT = "com.google.accompanist:accompanist-flowlayout:0.24.3-alpha"
헉 ㅠㅠㅠㅠㅠ 디자인 스펙 상 flexbox 를 사용하는게 아닌, 디자인처럼 한줄에 두개의 팀만 보이도록 구성되어야 해요 ㅜ.ㅜ 
제가 먼저 말했어야 했는데....

2022-02-28 03:31 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +                    .align(Alignment.BottomCenter),
여기 아래에 clickable 변수 추가해서 핸들링할 수 있지 않을까요?

2022-02-28 03:32 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +                state = if ((uiState.myTeam.team.isNotEmpty()) and (uiState.myTeam.count != -1)) YdsButtonState.ENABLED else YdsButtonState.DISABLED,
-1 이 선택 여부 맞죠~~? 직관성있게 상수로 두는게 어떨까요?

```suggestion
                state = if ((uiState.myTeam.team.isNotEmpty()) and (uiState.myTeam.count != TEAM_NOT_SELECTED)) YdsButtonState.ENABLED else YdsButtonState.DISABLED,
```

2022-02-28 03:36 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/TeamViewModel.kt
> +        setState { newState }
```suggestion
        setState { copy(team = team) }
```
이렇게도 가능해요!!

2022-02-28 03:36 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/TeamViewModel.kt
> +        setState { newState }
```suggestion
 setState { copy(team = team) }
```
이렇게도 가능해요!!

2022-02-28 03:37 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/TeamViewModel.kt
> +        setState { newState }
```suggestion
        val newState = uiState.value.copy(
            myTeam = uiState.value.myTeam.copy(
                count = teamNumber
            )
        )
        setState { copy(count = teamNumber) }
```
상동

2022-02-28 03:38 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +            repeat(team[0].count) { t ->
```suggestion
            repeat(team[0].count) { number ->
```

2022-02-28 03:38 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +        Text(text = "하나만 더 알려주세요", style = AttendanceTypography.h3, color = Color.Black)
나중에 stringResource 로 빼주세요!

2022-02-28 03:40 UTC, jsh-me requested changes
flexbox 부분 확인 부탁드려욥!

2022-03-01 14:51 UTC, junieberry commented on buildSrc/src/main/java/com/yapp/buildsrc/Dependencies.kt
> +        const val FLOW_LAYOUT = "com.google.accompanist:accompanist-flowlayout:0.24.3-alpha"
아하...

2022-03-04 03:33 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
> +            Team(navigateToMainScreen = { navController.navigate("member_main") })
```suggestion
            Team(navigateToMainScreen = { navController.navigate(AttendanceScreenRoute.MEMBER_MAIN.route) {
                        popUpTo(AttendanceScreenRoute.SIGNUP.route) { inclusive = true }
                    }
              })
```

2022-03-04 03:34 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
> +            route = "team"
```suggestion
            route = AttendanceScreenRoute.SIGNUP.route
```
이 화면에 이름 선택, 팀 선택이 둘다 들어가지요? 로그인 직후 최초 한번만 하는 행위이니 sign up으로 짓는게 어떨까용?

2022-03-04 03:36 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +                    color = Color.Black
```suggestion
                    color = Gray_1200
```

2022-03-04 03:38 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +fun TeamOption(uiState: TeamContract.TeamUiState, onTeamChoosed: (String) -> Unit) {
```suggestion
fun TeamOption(uiState: TeamContract.TeamUiState, onTeamClicked: (String) -> Unit) {
```
onTeamChosen or onTeamClicked ?

2022-03-04 03:39 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +    val rowNum = 2
```suggestion
```
안 쓰는 변수는 지우는게 어떨까용! ㅎ.ㅎ

2022-03-04 03:40 UTC, jsh-me reviewed
전반적으로 uiState.myTeam.team 이 자주 쓰이고 있는데, 변수로 빼는게 어떨까 싶어요!

2022-03-04 03:43 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +    val TEAM_NOT_SELECTED = -1
음,, 내부에는 상수 선언이 안되는 것 같네엽 ㅠ
우선은...외부에 선언해주는게 어떨까용?

``` kotlin
private object Team {
    const val TEAM_NOT_SELECTED = -1
}
```

2022-03-04 03:44 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +                onClick = { if ((uiState.myTeam.team.isNotEmpty()) and (uiState.myTeam.count != -1)) navigateToMainScreen() },
```suggestion
                onClick = { if ((uiState.myTeam.team.isNotEmpty()) and (uiState.myTeam.count != TEAM_NOT_SELECTED)) navigateToMainScreen() },
```

2022-03-04 03:46 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/model/TeamModel.kt
> +)
```suggestion
data class TeamModel(
    @SerializedName("team")
    val team: String = "",
    val count: Int = TEAM_NOT_SELECTED
) {
    companion object {
        const val TEAM_NOT_SELECTED = -1
    }
}
```

2022-03-04 03:50 UTC, jsh-me commented on presentation/src/main/res/values/strings.xml
> +    <string name="member_main_bottom_navigation_today_session_text">오늘의 세션</string>
```suggestion
    <string name="member_main_bottom_navigation_today_session_text">오늘 세션</string>
```

2022-03-04 03:54 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +                        state = if (uiState.myTeam.team == team.team) YdsButtonState.ENABLED else YdsButtonState.DISABLED,
```suggestion
                        state = if (uiState.selectedTeam.team == team.team) YdsButtonState.ENABLED else YdsButtonState.DISABLED,
```
"내가 현재 선택한 팀" 이라고 표현하는게 더 좋지 않을까 싶어 제안드려요

2022-03-04 03:55 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/model/TeamModel.kt
> +    val team: String = "",
```suggestion
    val teamType: TeamType = "",
```
enum type 으로 ios, and, web team 을 정의하는게 좋지 않을까 싶어요!
처음에 team 이 string type 이었다 보니 코드 읽었을을 때 어떤걸 담아내는 아이인지 헷갈렸던 것 같아요.

2022-03-04 03:58 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +    val team = uiState.teams.filter { it.team == uiState.myTeam.team }
```suggestion
    val selectedTeam = uiState.teams.filter { it.team == uiState.myTeam.team }
```

2022-03-04 03:59 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +            color = Color.Black
```suggestion
            color = Gray_1200
```

2022-03-04 07:43 UTC, junieberry commented on presentation/src/main/java/com/yapp/presentation/model/TeamModel.kt
> +    val team: String = "",
다른 기수 때 팀 이름이 변할 수 있지 않을까요? 이름만 `teamType`으로 바꾸는건 어떨까요!

2022-03-04 07:57 UTC, junieberry commented on presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
> +            route = "team"
이름 선택과 팀 선택 찢을 것 같습니다! 흠... `SIGNUPNAME`과 `SIGNUPTEAM`은 ㅇ떤가요..?

2022-03-04 08:11 UTC, junieberry commented on presentation/src/main/java/com/yapp/presentation/ui/member/signup/Team.kt
> +    val TEAM_NOT_SELECTED = -1
아하...

2022-03-04 09:39 UTC, toastmeister1 commented on presentation/src/main/java/com/yapp/presentation/model/TeamModel.kt
> +    val team: String = "",
이 부분 합의 되면 저도 코드에 반영하겠습니다!

2022-03-04 10:04 UTC, junieberry commented on presentation/src/main/java/com/yapp/presentation/model/TeamModel.kt
> +    val team: String = "",
일단 `teamType`과 `teamNum`으로 수정해뒀습니당

2022-03-09 07:45 UTC, junieberry commented
@jsh-me 세희님 수정한 부분 혹시 한번 확인해주실 수 있으신가요?

2022-03-13 07:01 UTC, jsh-me approved these changes

2022-03-13 07:49 UTC, jsh-me commented
제가 머지할게여 이거! 수고 많으셨어유~~~

2022-03-13 07:49 UTC, merged