Feature/implement qr scan
YAPP-admin/attendance-android pull request #58
Opened 2022-03-03 21:45 UTC by jihee-dev

**Description**
- QR 출석 스캔 화면 구현
  - 인식 범위 적용 X(전화면에서 QR 스캔 가능), 인식 범위 표현만 되어 있는 상태입니다

**Screen Shots**

| Screen Shot | Screen Shot |
| ----------- | ----------- |
|             |             |
![image](https://user-images.githubusercontent.com/42907876/156657541-d7de2682-c3bf-48f9-bdf1-d5cc97ad3026.png)

**Check List**

- [ ] CI/CD 통과여부
- [ ] Develop Mege 시 Squash and Merge 형태로 넣어주세요!
- [ ] 1Approve 이상 Merge
- [ ] Unit Test 작성
- [ ] 연관된 이슈를 PR에 연결해주세요.

2022-03-04 04:09 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
> +                navController = navController
navController 자체를 다 넘겨주지 말고, 우선은 람다로 이벤트를 전달하도록 만드는건 어떨까요?

2022-03-04 04:11 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +        }
```suggestion
        } else navController.popBackStack()
```

2022-03-04 04:12 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +    var code = remember { mutableStateOf("") }
```suggestion
    var code by remember { mutableStateOf("") }
```
위와 동일한 컨벤션으로 갖는게 좋을 것 같아요

2022-03-04 04:12 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +                    this.scaleType = PreviewView.ScaleType.FILL_CENTER
```suggestion
                   scaleType = PreviewView.ScaleType.FILL_CENTER
```

2022-03-04 04:15 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +                .fillMaxHeight(),
```suggestion
                .fillMaxSize(),
```

2022-03-04 04:16 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +                    }
try-catch가 꼭 필요한가용?

2022-03-04 04:17 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +                                    //Log.d("QrCodeAnalyzer", "Points: ${qrCode.cornerPoints}")
```suggestion
```

2022-03-04 04:20 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +                        QrCodeAnalyzer { qrCodes ->
리컴포지션이 많이 일어나는 구조에서 QrCodeAnalyzer 는 클래스여서 호출할 때마다 클래스가 생성될 것 같아요. 좋지 않은 형태인데 개선해보는건 어떨까ㅏ요?

2022-03-04 04:21 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +                        QrCodeAnalyzer { qrCodes ->
저라면 flow 사용할 것 같네요

2022-03-04 04:24 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +    var code = remember { mutableStateOf("") }
엇 보니 code 를 사용하는 곳이 없네요. 지우는게 어떨까요!

2022-03-04 04:25 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +                val cameraExecutor: ExecutorService = Executors.newSingleThreadExecutor()
스레드를 매번 생성하나요?

2022-03-04 04:27 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeAnalyzer.kt
> +        if (currentTimeStamp - lastAnalyzedTimeStamp >= TimeUnit.SECONDS.toMillis(1)) {
3초 정도로 두고, 상수로 빼냅쉬당!

2022-03-04 04:29 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +                        }
```suggestion
                        .apply {
                            setAnalyzer(cameraExecutor, barcodeAnalyzer)
                        }
```

2022-03-04 04:30 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +    LaunchedEffect(key1 = true) {
coroutinescope 를 이용할 수는 없을까요? Key 값이 변하지 않으니까요!

2022-03-04 04:33 UTC, jsh-me requested changes
1. Log 는 전부 제거하는게 좋을 것 같아요.
2. 주석은 지워주셨으면 좋겠습니다! 
3. 명시되어있는 타입들 전부 제거하는게 좋겠습니다.
4. 가능하다면 카메라 관련 로직은 딜리버디처럼 util 로 빼냈으면 좋겠습니다 ㅎ.ㅎ
5. ~~qr 인증 관련 로직도 반드시 util로 빼냈으면 좋겠습니다!~~
6. ~~QRCodeAnalyzer 코드를 hot observable 처럼 개선했으면 좋겠습니다.~~
콜백을 이용해서 구현한 이유는 이해합니다만ㅠ 메모리 관리도 전혀 안되어있고, 무작위로 스레드를 생성하고 있어 불안하네용

2022-03-04 08:08 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +    var code = remember { mutableStateOf("") }
도메인 로직 엮을 때 사용하게 될 것 같아서 만들어놓고 토스트만 띄우도록 사용하고 있었어요! 우선 제거해 두는 게 좋을까요?

2022-03-04 08:22 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +        }
요 부분 카메라 권한 없을 때 바로 끄는 것보단 권한 재요청하고 권한이 필요한 이유에 대해서 설명하는 곳이 필요할 것 같아요
아직 권한 관련해서 재요청하고 이런 부분 처리가 안 되어 있어서 같이 수정해서 다시 커밋 올리겠습니다

2022-03-04 08:22 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +                    }
IllegalStateException이나 IllegalArgumentException이 발생할 수도 있다고 해서 try-catch로 묶어두었어요!

2022-03-04 08:37 UTC, jihee-dev commented
> 4. 카메라 관련 로직이 어떤 걸 말씀하시는 걸까요? 권한 가져오는 부분이 맞나용?
> 5. QR 관련 로직은.. 안드로이드 뷰의 update 쪽 말씀하시는 게 맞을까요? ㅠㅡㅠ
> 6. 요 부분 더 찾아보면서 개선해 보겠습니다! 넘 막 짠 것 같네요 ㅠㅠ

2022-03-05 07:24 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +    var code = remember { mutableStateOf("") }
아항 ㅎㅎ 그럼 두는걸로!

2022-03-05 07:25 UTC, jsh-me commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +                    }
runCatching 사용해보는건 어떨까요!

2022-03-07 10:52 UTC, toastmeister1 commented on presentation/src/main/java/com/yapp/presentation/ui/member/qrcodescanner/QrCodeScanner.kt
> +            .fillMaxHeight()
```suggestion
            .fillMaxSize()
```

2022-03-13 21:37 UTC, merged